<h2>1. ACEITAÇÃO DOS TERMOS DE USO</h2>
<p>1.1 Para a utilização dos serviços oferecidos por Mestre Obra disponibilizados em http://www.mestreobra.com.br (“Site”) é necessária a leitura e aceitação dos presentes TERMOS E CONDIÇÕES DE USO (“Termos de Uso”).</p>
<p>1.2 Mestre Obra apresenta aos usuários em geral dos seus serviços, sendo eles Contratantes e Profissionais e Empresas prestadores de serviços (denominados em conjunto como “Usuários”), por intermédio deste Termos de Uso, as condições essenciais para o uso dos serviços oferecidos no Site.</p>
{{--<p>1.3 Mestre Obra é um provedor de serviços hospedado sob domínio www.mestreobra.com.br, de propriedade da XXXXXXXXXX, registrada no CNPJ n° XX.XXX.XXX/0001-XX e disponibilizado através da URL http://www.mestreobra.com.br. Com sede localizada na Rua Doutor Penteado de Almeida, 687, Centro, CEP 84010-240, cidade de Ponta Grossa, Estado do Paraná, telefone de contado (42) 3028-0191 e email de contato contato@mestreobra.com.br .</p>--}}

<h2>2. IDADE E CAPACIDADE LEGAL</h2>
<p>2.1 Os serviços do Mestre Obra estão disponíveis para pessoas físicas e pessoas jurídicas regularmente inscritas nos cadastros de contribuintes federal e estaduais que tenham capacidade legal para contratá-los.</p>
<p>2.1.1 O Usuário, se pessoa física, declara ser plenamente capaz para contratar os Serviços. Assim, as pessoas que não gozem de capacidade legal, inclusive os menores de 18 anos, estão impedidos de contratar os Serviços.</p>
<p>2.1.2 O Usuário, sendo pessoa jurídica, o fará na figura do seu representante legal ou pessoa autorizada pela empresa.</p>
<p>2.2 Não podem utilizar os serviços do Mestre Obra, assim, pessoas que não se enquadrem nestas condições ou pessoas que tenham sido inabilitadas do Mestre Obra, temporária ou definitivamente. Ficam, desde já, os Usuários advertidos das sanções legais cominadas no Código Civil.</p>
<p>2.3 É vedada a criação de mais de um cadastro por Usuário. Em caso de multiplicidade de cadastros elaborados por um só Usuário, o Mestre Obra reserva-se o direito de, a seu exclusivo critério e sem necessidade de prévia anuência dos ou comunicação aos Usuários, inabilitar todos os cadastros existentes e impedir eventuais cadastros futuros vinculados a estes.</p>
<p>2.3.1 Somente será permitida a vinculação de um cadastro a um CPF, um telefone e um email, não podendo haver duplicidade de dados em nenhum caso.</p>
<p>2.4 O Mestre Obra pode unilateralmente excluir o cadastro dos Usuários que não se enquadrem nestas condições.</p>

<h2>3. SERVIÇOS</h2>
<p>3.1 O serviço oferecido pelo Mestre Obra consiste em conectar usuários de internet para compra e/ou venda de serviços relacionados à construção civil em seu Site. Desta forma, o Mestre Obra apenas oferece um ambiente virtual (“Plataforma”) para que o usuário por sua conta e risco compre e/ou venda serviços relacionados ao setor de construção civil, como elaboração de projetos, execução de obras, demolições e reformas, reparos e manutenção, acabamentos e pinturas. O contato, a negociação, a troca de informações e qualquer outra atividade realizada entre Usuários é feita sem a intervenção do Mestre Obra. Mestre Obra não é fornecedor dos serviços contratados pelos seus usuários.</p>
<p>3.2 O Usuário que utiliza o site Mestre Obra para vender ou comprar serviços, o faz por sua conta e risco, sem que o Mestre Obra seja responsável pela veracidade das informações e dados fornecidas pelos Usuários, nem pela qualidade e demais problemas que possam surgir como resultado dos serviços prestados. O Mestre Obra não participa e/ou interfere, de qualquer forma, na negociação e/ou efetivação de quaisquer transações.</p>
<p>3.3 O Mestre Obra não intervirá em nenhum caso nas negociações levadas a cabo entre Usuários, permanecendo à margem das mesmas em todo momento, pelo que não será responsável, em nenhum caso, do incumprimento das obrigações do Contratante com o Profissional ou Empresa, eximindo expressamente o Cliente e o Profissional, o Mestre Obra, de qualquer desavença que possa surgir entre ambos.</p>
<p>3.4 É de responsabilidade exclusiva do Contratante a comprovação da idoneidade dos serviços oferecidos pelo Profissional ou Empresa e de que os mesmos se adaptam às necessidades do Contratante. O Contratante assume igualmente a responsabilidade de examinar a titulação, capacitação e competência profissional do Profissional ou Empresa, assim como de realizar o oportuno acompanhamento sobre o trabalho encomendado, os materiais, adequação, prazos e cronogramas, estética ou não, ao requerido pelo Contratante e acordado no oportuno orçamento. Em nenhum caso o Mestre Obra controlará nem intervirá na execução dos trabalhos realizados pelo Profissional ou Empresa, nem na adequação, qualidade ou resultado dos mesmos, assim sendo o Mestre Obra exclui com toda a extensão permitida pelo ordenamento jurídico, qualquer responsabilidade pelos danos e prejuízos de toda natureza que possam dever-se a execução ou resultado do trabalho encomendado ao Profissional ou Empresa, bem como o Contratante expressamente excluir o Mestre Obra de qualquer discrepância, responsabilidade, dano, prejuízo ou deterioro como resultado da contratação do trabalho realizado pelo Profissional ou Empresa.</p>
<p>3.5 O Mestre Obra busca se informar sobre a qualidade e idoneidade dos Profissionais e Empresas divulgados no Site, mas não se responsabiliza pelos serviços prestados ou divulgados. Os Usuários realizadores de serviço, só poderão se cadastrar e se candidatar para a realizar serviços, aos quais esteja devidamente capacitado, o Mestre Obra não é responsável pela capacitação desses Usuários.</p>
<p>3.6 Por se tratar de negociações realizadas por meio eletrônico entre dois Usuários que não se conheciam previamente à negociação, o Mestre Obra recomenda que toda transação seja realizada com cautela e prudência.</p>
<p>3.7 Caso um ou mais Usuários inicie qualquer tipo de reclamação ou ação legal contra outro ou outros Usuários, todos e cada um dos Usuários envolvidos nas reclamações ou ações eximem de toda responsabilidade o Mestre Obra e seus diretores, gerentes, empregados, agentes, operários, representantes e procuradores.</p>

<h2>4. CADASTRO</h2>
<p>4.1 Durante o cadastro é necessário o preenchimento completo de todos os dados pessoais solicitados no Mestre Obra para que Usuário esteja habilitado a utilizar os serviços do Site.</p>
<p>4.2 A responsabilidade de fornecer, atualizar e garantir a veracidade dos dados cadastrais é unicamente dos Usuários, não cabendo ao Mestre Obra qualquer tipo de responsabilidade civil e criminal resultante de dados inverídicos, incorretos ou incompletos fornecidos pelos Usuários.</p>
<p>4.3 O Mestre Obra se reserva o direito de utilizar todos os meios válidos e possíveis para identificar seus Usuários, bem como de solicitar dados adicionais e documentos que estime serem pertinentes a fim de conferir os dados pessoais informados.</p>
<p>4.4 Caso o Mestre Obra considere um cadastro, ou as informações nele contidas, suspeito de conter dados errôneos ou inverídicos, o Mestre Obra se reserva o direito de suspender, temporária ou definitivamente, o Usuário responsável pelo cadastramento, assim como impedir e bloquear qualquer publicidade ou cadastro de Serviços e cancelar anúncios publicados por este, sem prejuízo de outras medidas que entenda necessárias e oportunas. No caso de aplicação de quaisquer destas sanções, não assistirá aos Usuários direito a qualquer tipo de indenização ou ressarcimento por perdas e danos, lucros cessantes ou danos morais.</p>
<p>4.5 O Usuário acessará sua conta por meio de login e senha, comprometendo-se a não informar a terceiros esses dados, responsabilizando-se integralmente pelo uso que deles seja feito.</p>
<p>4.6 O Usuário compromete-se a notificar o Mestre Obra imediatamente, pelo email contato@mestreobra.com.br, a respeito de qualquer uso não autorizado de sua conta. O Usuário será o único responsável pelas operações efetuadas em sua conta, uma vez que o acesso só será possível mediante a utilização de senha de seu exclusivo conhecimento.</p>
<p>4.7 Em nenhuma hipótese será permitida a cessão, a venda, o aluguel ou outra forma de transferência da conta. Não se permitirá, ainda, a criação de novos cadastros por pessoas cujos cadastros originais tenham sido cancelados por infrações às políticas de do Mestre Obras.</p>
<p>4.8 O login que o Usuário utiliza no Mestre Obra não poderá guardar semelhança com o nome Mestre Obra. Tampouco poderá ser utilizado qualquer apelido que insinue ou sugira que os Serviços serão prestados pelo Mestre Obra ou que fazem parte de promoções suas. Também serão eliminados apelidos considerados ofensivos ou que infrinjam a legislação em vigor.</p>
<p>4.9 O Mestre Obra se reserva o direito de, unilateralmente e sem prévio aviso, recusar qualquer solicitação de cadastro e de cancelar um cadastro previamente aceito.</p>

<h2>5. SOLICITAÇÃO DE ORÇAMENTO</h2>
<p>5.1 Mestre Obra oferece aos Contratantes a possibilidade de solicitar orçamentos aos Profissionais e Empresas cadastradas no Site. Para isto, o Contratante registrado proporcionará informações e características do trabalho que deseja solicitar um orçamento e se compromete que estas sejam honestas e ajustadas à realidade. Em qualquer caso, os Usuários serão os únicos responsáveis pelas informações falsas ou inexatas que disponibilizem, bem como pelos prejuízos que possam causar ao Mestre Obra ou a terceiros pelas referidas informações.</p>
<p>5.2 Ao solicitar um orçamento, o Contratante está de acordo que seus dados de contato e conteúdo sejam cedidos a terceiros. Desta forma, o Mestre Obra fornecerá tais dados a, pelo menos, dois Profissionais ou Empresas, com a finalidade de que contatem o Contratante para fornecer-lhe o orçamento solicitado ou informação sobre o serviço solicitado. A referida comunicação de dados pessoais é necessária para que se leve a cabo o serviço solicitado pelo Usuário e se encontra regulada pela Política de Privacidade.</p>
<p>5.3 O Contratante não está obrigado a aceitar nenhum orçamento que lhe tenha sido fornecido por Profissionais ou Empresas contatados através do Mestre Obra.</p>
<p>5.4 O Contratante poderá informar ao Mestre Obra qualquer irregularidade detectada com relação aos Profissionais e Empresas que se anunciam através do Site, apesar de que o Mestre Obra não se responsabiliza pelos trabalhos nem pelo profissionalismo e qualificação dos Profissionais e Empresas anunciados no Site. No caso de que o Mestre Obra tenha conhecimento de que algum Usuário esteja infringindo a legalidade vigente, procederá imediatamente o cancelamento de sua conta.</p>

<h2>6. POLÍTICA DE CONTEÚDOS</h2>
<p>6.1 Os Contratantes poderão inserir opiniões e comentários relativos aos Profissionais e Empresas inscritos no Site. Tais opiniões poderão estar baseadas naqueles serviços prestados como consequência do uso do Site ou em outros realizados à margem do Site. O Mestre Obra possui o direito de publicar, sintetizar, resumir ou abreviar o conteúdo das opiniões realizadas pelos Contratantes.</p>
<p>6.2 O Usuário compromete-se a não transmitir, difundir ou colocar à disposição de terceiros, conteúdos, comentários ou opiniões que, a título indicativo e não meramente exaustivo:</p>
<ul>
    <li>De qualquer forma sejam contrários, menosprezem ou atentem contra os direitos fundamentais, as liberdades públicas reconhecidas constitucionalmente nos tratados internacionais e no restante da legislação vigente.</li>
    <li>Induzam, incitem ou promovam atuações, atitudes delitivas, denigretórias, difamatórias, infamantes, violentas ou, em geral, contrárias à lei, à moral e aos bons costumes geralmente aceitos e à ordem pública.</li>
    <li>Não tenham em conta os bens ou serviços desenvolvidos pelo Profissional ou Empresa; ou comentários que não tenham qualquer valor qualitativo (por exemplo, “o trabalho ainda não foi terminado”).</li>
    <li>Incorporem, ponham à disposição ou permitam acessar a produtos, elementos, mensagens ou serviços delitivos, violentos, ofensivos, nocivos, degradantes ou, em geral, contrários à lei, à moral, aos bons costumes geralmente aceitos ou à ordem pública.</li>
    <li>Induzam ou possam induzir a terceiros a um estado inaceitável de ansiedade ou temor.</li>
    <li>Sejam injuriosos, ofensivos ou degradantes.</li>
    <li>Não se correspondam com o trabalho desenvolvido pelo Profissional ou Empresa.</li>
    <li>Sejam contrários ao direito de honra, à intimidade pessoal e familiar ou a própria imagem das pessoas.</li>
    <li>Infrinjam a normativa vigente referente ao segredo das comunicações.</li>
    <li>Sejam relativos à publicidade de outros sites que sejam concorrentes do Site ou seus anunciantes.</li>
    <li>Sejam falsos ou não se correspondam à realidade.</li>
    <li>Tratem-se de publicidade ilícita, enganosa ou desleal.</li>
    <li>Provoquem por suas características (tais como formato, extensão, etc.) dificuldades no funcionamento normal dos serviços.</li>
</ul>
<p>6.3 O Mestre Obra reserva-se o direito de retirar do Site todos aqueles comentários e opiniões que não estejam de acordo com os presentes Termos de Uso, e em nenhum caso, faz-se responsável pelos conteúdos ou opiniões manifestadas pelo Usuário no Site.</p>
<p>6.4 Assim mesmo, o Mestre Obra reserva-se o direito de modificação do conteúdo publicado pelo Profissional ou Empresa no Site, aos únicos efeitos publicitários de atribuir-lhe uma melhor apresentação e distribuição no Site, e de destacar as características dos serviços oferecidos, bem como para adequar o conteúdo ao estilo e aos mínimos de qualidade do Mestre Obra. A tais efeitos, Profissional e Empresa autorizam o Mestre Obra a, de forma gratuita, realizar ditas modificações ou adaptações, a reproduzir livremente, distribuir, publicitar ou explorar por qualquer forma ou meio dito conteúdo publicado pelo Profissional ou Empresa, renunciando a quaisquer direitos de conteúdo econômico que pudessem lhe corresponder, em conceito de compensação ou qualquer outro título.</p>
<p>6.5 Além disso, o Usuário concorda em NÃO:</p>
<p>6.5.1 Obter, guardar, divulgar, comercializar e/ou utilizar dados pessoais sobre outros Usuários, seja para a indicação posterior de profissionais e empresa ou para qualquer outro motivo, com ou sem fins comerciais ou ilícitos;</p>
<p>6.5.2 Usar meios automáticos, incluindo spiders, robôs, crawlers, ferramentas de captação de dados ou similares para baixar dados do Site - exceto quando for o caso de ferramentas de busca na Internet (ex. Google Search) e arquivos públicos não comerciais (ex. archive.org);</p>
<p>6.5.3 Burlar de qualquer forma que seja o sistema, mecanismo e/ou Site do Mestre Obra; seja para conseguir informações de Usuários para utilização por terceiros ou para qualquer outro fim;</p>
<p>6.5.4 Incluir meios de contato como telefone, e-mail, endereço e outras formas externas de comunicação nas ofertas.</p>

<h2>7. USO DOS SERVIÇOS E DO SITE</h2>
<p>7.1 Os Usuários comprometem-se a utilizar os serviços oferecidos através do Site em conformidade com a legislação vigente, os presentes Termos de Uso, as condições particulares que se estabeleçam para certos serviços e demais avisos e instruções postos a seu conhecimento bem como à moral e os bons costumes geralmente aceitos e à ordem pública.</p>
<p>7.2 Os Usuários renunciam a: utilizar qualquer dos materiais e informações contidos neste Site com fins ilícitos ou expressamente proibidos nos presentes Termos de Uso bem como nas condições particulares que venham a aderir ou em desfavor dos direitos e interesses do Mestre Obra, seus membros ou terceiros, devendo responder ante estes no caso de que incumpram referidas obrigações, ou de qualquer modo (incluída a introdução ou difusão de “vírus informáticos”), causem dano, inutilizem, sobrecarreguem, deteriorem ou impeçam a utilização normal dos materiais e informações contidos no Site, dos sistemas de informação ou dos documentos, arquivos e de todo tipo de conteúdo armazenado em qualquer equipamento informático (hacking) do Mestre Obra, de seus membros ou de qualquer Usuário do Site.</p>
<p>7.2.1 O Usuário está ciente de que todos as postagens disponíveis no Site são produzidos e disponibilizados por terceiros, sem que haja qualquer tipo de controle, monitoramento ou verificação prévia do Mestre Obra. O Mestre Obra não controla, não edita, não monitora e não é, de qualquer forma, responsável pelas postagens disponibilizadas através do seu Site de serviços, mensagens, comentários, publicidade, arquivos, imagens, fotos, vídeos, sons ou qualquer outro material disponibilizado através dos Anúncios de Tarefas e/ou Serviços ou a eles relacionados ("Conteúdo") e submetidos ao Site por seus Usuários. O Usuário também concorda que ao utilizar o Site poderá se expor a Conteúdo eventualmente ofensivo, inexato, enganoso ou, de qualquer outro modo, censurável.</p>
<p>7.2.1.1 Mesmo ciente de que o Mestre Obra não realiza nenhuma triagem prévia do Conteúdo e não o submete a um processo prévio de aprovação, o Usuário reconhece que o Mestre Obra terá o direito (mas não a obrigação) de, a seu exclusivo critério, recusar, excluir ou alterar qualquer Conteúdo, Imagem, Vídeo e/ou Anúncio disponibilizado no Site, seja por violação aos Termos de Uso ou por quaisquer outras razões de ordem ética, legal ou moral.</p>
<p>7.2.2 O Usuário é o único responsável por todo o Anúncio e/ou Conteúdo de sua autoria ou por ele divulgado, transmitido por e-mail ou associado a link disponibilizado no/ou através do Site; assim como pelo seu uso, divulgação ou publicação, devendo o Usuário manter o Mestre Obra, seus funcionários, parceiros e controladores livres e indenes de toda e qualquer consequência advinda de seus atos/ omissões, inclusive em relação a terceiros.</p>

<h2>8. MODIFICAÇÕES DOS TERMOS E CONDIÇÕES GERAIS</h2>
<p>8.1 Mestre Obra poderá alterar, a qualquer tempo e a seu único e exclusivo critério, estes Termos de Uso. Os novos Termos de Uso entrarão em vigor 10 (dez) dias depois de publicados na Plataforma. No prazo de 6 (seis) dias contados a partir da publicação das modificações, o Usuário deverá informar, por email, caso não concorde com os termos alterados. Nesse caso, o vínculo contratual deixará de existir, desde que não haja contas ou dívidas em aberto. Não havendo manifestação no prazo estipulado, entender-se-á que o Usuário aceitou totalmente os novos Termos de Uso, e o contrato continuará vinculando as partes.</p>
<p>8.2 As alterações não vigorarão em relação a negociações e anúncios já iniciados ao tempo em que tais alterações sejam publicadas. Apenas para estes, os Termos de Uso valerão com a redação anterior.</p>

<h2>9. POLÍTICA DE PRIVACIDADE</h2>
<p>9.1 O Usuário desde já autoriza o Mestre Obra, a seu critério, preservar, armazenar todos os Anúncios e/ou Conteúdos submetidos ao Site, bem como todos os seus dados pessoais, cadastrais e de acesso, a exemplo de endereços de e-mail, endereços de IP (Internet Protocol), informações de data e horário de acesso, entre outras informações. O Usuário também autoriza o Mestre Obra a informar e/ou divulgar estes dados em caso de exigência legal ou se razoavelmente necessárias para: cumprir com o devido processo legal; fazer cumprir estes Termos de Uso; responder a alegações de suposta violação de direitos de terceiros e para proteger os direitos, a propriedade ou a segurança de terceiros ou do próprio Mestre Obra e de seus Usuários.</p>
<p>9.2 A utilização do Site implica no consentimento do Usuário para coleta, armazenamento e uso das informações pessoais fornecidas, cadastrais, de acesso e suas atualizações.</p>
<p>9.3 O Mestre Obra poderá utilizar cookies para administrar as sessões, navegações, acessos e cadastros dos Usuários e armazenar preferências, rastrear informações, entre outros. Cookies poderão ser utilizados independentemente de cadastro do Usuário.</p>
<p>9.3.1 "Cookies" são pequenos arquivos de texto transferidos via servidor para o disco rígido e armazenados no computador do Usuário. Cookies podem coletar informações como data e horário de acesso, histórico de navegação, preferências e nome do usuário.</p>
<p>9.4 O Usuário tem a opção de aceitar ou recusar o uso de cookies em seu computador, independente de cadastro no Site, configurando seu navegador como desejar. A recusa do uso de cookies pode, contudo, resultar na limitação do acesso do Usuário a certas ferramentas disponíveis no Site, dificuldades no acesso ("login") e na ferramenta de comentários.</p>
<p>9.5 O Site poderá, eventualmente, conter links para sites de terceiros. O Mestre Obra não se responsabiliza pelo conteúdo ou pela segurança das informações do Usuário quando acessar sites de terceiros. Tais sites podem possuir suas próprias políticas de privacidade quanto ao armazenamento e conservação de informações pessoais, completamente alheias à do Mestre Obra.</p>
<p>9.6 O Mestre Obra poderá trabalhar com empresas terceirizadas de propaganda para a divulgação de anúncios durante seu acesso ao Site. Tais empresas poderão coletar informações sobre as visitas de Usuários ao Site, no intuito de fornecer anúncios personalizados sobre bens e serviços do interesse do Usuário. Tais informações não incluem nem incluirão nome, endereço, e-mail ou número de telefone do Usuário.</p>
<p>9.7 O Mestre Obra se reserva o direito de reter informações pelo período que entender necessário para o bom cumprimento de seus negócios, mesmo após o encerramento da conta do Usuário.</p>
<p>9.8 As informações referentes ao Serviço são mantidas em uma base de dados escolhida pelo Mestre Obra e que atende aos padrões de segurança atuais.</p>
<p>9.9 O Usuário desde já declara estar ciente de que o Mestre Obra não assume nenhuma responsabilidade em caso de roubo, perda, alteração ou uso indevido de suas informações pessoais e do Conteúdo como um todo, inclusive na hipótese de informações fornecidas a prestadores de serviços terceirizados ou a outros Usuários e na hipótese de descumprimento destes Termos de Uso por prestadores de serviços terceirizados.</p>
<p>9.10 O Usuário poderá solicitar a qualquer momento o cancelamento do recebimento de quaisquer e-mails transacionais ou promocionais do Mestre Obra enviando um e-mail para contato@mestreobra.com.br.</p>

<h2>10. DIREITOS DE PROPRIEDADE INTELECTUAL</h2>
<p>10.1 Os elementos e/ou ferramentas encontrados no Site, com exceção dos Conteúdos e/ou Anúncios submetidos por Usuários, são de titularidade ou licenciados para o Mestre Obra, sujeitos aos direitos intelectuais de acordo com as leis brasileiras e tratados e convenções internacionais dos quais o Brasil seja signatário. Apenas a título exemplificativo, entendem-se como tais: textos, softwares, scripts, imagens gráficas, fotos, sons, músicas, vídeos, recursos interativos e similares, marcas, marcas de serviços, logotipos e "look and feel".</p>
<p>10.2 Os elementos e/ou ferramentas que são disponibilizados para o Usuário no Site os são tão somente no estado em que se encontram e apenas para sua informação e uso pessoal na forma designada pelo Mestre Obra. Tais elementos e/ou ferramentas não podem ser usados, copiados, reproduzidos, distribuídos, transmitidos, difundidos, exibidos, vendidos, licenciados ou, de outro modo, explorados para quaisquer pessoa, sem o consentimento prévio e por escrito do Mestre Obra.</p>
<p>10.3 O Mestre Obra reserva a si todos os direitos que não foram expressamente previstos em relação ao Site, aos seus elementos e/ou ferramentas. O usuário compromete-se a não usar, reproduzir ou distribuir quaisquer elementos e/ou ferramentas que não sejam expressamente permitidos pelo Mestre Obra - inclusive o uso, reprodução ou distribuição para comerciais dos Anúncios e/ou Conteúdos extraídos do Site. Caso o Usuário faça qualquer cópia, seja ela via download ou impressão, dos elementos e/ou ferramentas do Mestre Obra para uso exclusivamente pessoal, deverá preservar todos os direitos de propriedade intelectual inerentes. O Usuário concorda em não burlar, desativar ou, de alguma forma, interferir em recursos e/ou ferramentas relacionados à segurança do Site, sob pena de incorrer nas medidas judiciais cabíveis.</p>

<h2>11. INDENIZAÇÃO</h2>
<p>11.1 O Usuário indenizará o Mestre Obra suas filiais, empresas controladas, controladores diretos ou indiretos, diretores, administradores, colaboradores, representantes e empregados, inclusive quanto a honorários advocatícios, por qualquer demanda promovida por outros Usuários ou terceiros, decorrentes das atividades do primeiro no Site, de quaisquer descumprimentos, por aquele, dos Termos de Uso e das demais políticas do Mestre Obra ou, ainda, de qualquer violação, pelo Usuário, de lei ou de direitos de terceiros.</p>

<h2>12. LEGISLAÇÃO APLICÁVEL E FORO DE ELEIÇÃO</h2>
<p>12.1 Todos os itens destes Termos são regidos pelas leis vigentes na República Federativa do Brasil.</p>
{{--<p>12.2 Para todos os assuntos referentes à interpretação, ao cumprimento ou a qualquer outro questionamento relacionado a estes Termos, as partes concordam em se submeter ao Foro da Comarca de São Paulo.</p>--}}